### ISSUE TITLE
Making the image snap back if you zoom out, pan, and then zoom back in

### ISSUE THREAD

**Issue by mkaatman** [cmulders/Leaflet.Zoomify#1]
@cmulders Your version of this plugin seems to work great. Thank you for the hard work!

Would it be possible to add support so that the image snapped back into place if you pan or zoom beyond the canvas?

Take a look at this implementation and notice that if you try to pan the image too far it snaps back.
http://kempe.net/blog/2014/06/14/leaflet-pan-zoom-image.html

**Comment by cmulders** [comment]
@mkaatman Yes you can! The bounds of the image are calculate and stored by the plugin in it's options. So if you look at the example.html file, you see the following:

``` javascript
//Setting the view to our layer bounds, set by our Zoomify plugin
map.fitBounds(layer.options.bounds);
```

The layer.options.bounds could also be used to use the `L.map.setMaxBounds`, resulting in:

``` javascript
map.setMaxBounds(layer.options.bounds);
```

**Comment by mkaatman** [comment]
@cmulders That seems to work great. Thanks!
