### ISSUE TITLE
Options for limit zoom in and zoom out

### ISSUE THREAD

**Issue by pmezhuev** [cmulders/Leaflet.Zoomify#2]
Thanks for your work! There is a way to limit the zoom to prevent excessive increase or decrease image?

**Comment by cmulders** [comment]
I think you should use the regular tile layer options, as explained here: http://mourner.github.io/Leaflet/reference.html#tilelayer-minzoom

Hope this helps! Otherwise, please elaborate on the issue or option you desire.

**Comment by pmezhuev** [comment]
Yes, it works. Thanks!
