### ISSUE TITLE
feature request: set offset and scale

### ISSUE THREAD

**Issue by jvolker** [cmulders/Leaflet.Zoomify#4]
I need to adjust the position and scale of the Zoomify layer in order to calibrate it and be able to use geo coordinates on it. I couldn't find an option to set offset and scale for this in the plugin or in Leaflet.

I saw it was already added to [this fork of the plugin](https://github.com/kurtbeheydt/Leaflet.Zoomify/tree/custom_zoom_center_position_onAdd), which is unfortunately not updated to Leaflet 1.0.
As I'm not even sure if the plugin is the component that should solve it, I also [cross posted here](http://stackoverflow.com/questions/42706953/how-to-offset-and-scale-a-custom-tile-layer-in-leaflet) asking for more general advice and other strategies.

Thanks!

**Comment by cmulders** [comment]
Not sure if that will be the task of this plugin. Do you only want to display your own zoomify image or project it over another tile layer? If it is the former, you can use a custom CRS to accomplish custom scaling and offset. See some other work of mine: https://github.com/cmulders/cask_virtualmicroscopy/blob/gh-pages/annotated_zf/index.html or live version: http://anatomie01.lumc.nl/microscopy/zf/?zoom=0&lat=-0.000310&lng=0.000750

In particular this code:
```js
//Slide parameters, res in m/pixel
	var slide = {id:'zebravis', width:921600, height:380928, res:1.627e-9};

//Custom CRS to translate between pixels and meters.
    L.CRS.Slide = L.extend({}, L.CRS.Simple,{
        transformation: (function(){
            var longestSide = Math.max(slide.width, slide.height);
            var maxZoom = Math.ceil(Math.log(longestSide / 256) / Math.log(2));
            var correctedRes = slide.res*Math.pow(2, maxZoom);
            return new L.Transformation(1 / correctedRes, 0, -1 / correctedRes, 0)
        })()
    });
```

Check the documentation for custom crs for the details. 
Note: this code was for leaflet-1.0beta

**Comment by jvolker** [comment]
Thanks a lot!

It's only going to be one Zoomify image and overlays (markers and paths), but no other base layer. 
The CRS and your example is really helpful, thanks! ~~I've got two questions though:~~

- ~~How do you calculate the `res:1.627e-9`? Is this a pixels/meter ratio?~~
- ~~What type of coordinates are you using in `annotations.js`? Are these geo coordinates, pixel coordinates or even something else?~~ 

**Update:** the comments in your code answer it. I'm going to look into it.

**Comment by cmulders** [comment]
Good luck! If you want any help, please let me know. Was quite a challenge to figure it all out the first time. But if you get the calculations right, it works like a charm. 

Let me know if the plugin itself does not behave like expected :).

**Comment by jvolker** [comment]
Thanks a lot!
Your advice would be highly appreciated. 

- Using your code and changing the dimensions and resolution of the slide/map layer will probably not be enough. Your code adjusts the zoom, but how do I translate along lat/long?
- Do I have to change the projection from `L.Projection.LonLat` (being used by `L.CRS.Simple`) to `L.Projection.SphericalMercator` being used by my source or should I even use and extend `L.CRS.EPSG3857` instead of  `L.CRS.Simple`? 

Thanks again!

**Comment by cmulders** [comment]
After some thought, the problem is not really trivial. The issue is that the Zoomify plugin now loads the map at '0.0'. I thought that using a offset in the CRS transformation to a custom origin it could be done. However, the tile layer starts to load those tiles instead (e.g. requesting not Tile 0,0 but 14,15). Therefore, the (Zoomify) plugin or leaflet itself needs to correct for that. 
Not only that, if your origin is not on a tile boundary, then your tiles also need to be shifted again to accommodate the misalignment.

The image I showed, is a independent image without any other reference, therefore the 0,0 origin was fine for me. 

Maybe also ask in https://gitter.im/Leaflet/Leaflet !

**Comment by jvolker** [comment]
Thanks. After all, I went on a totally different route without Zoomify, which I think makes more sense in my case.  
I used [QGIS](https://www.qgis.org/) to geo-reference my custom layer and export it as GeoTIFF following [this tutorial][1]. I uploaded it to [Mapbox](https://www.mapbox.com) and baked it into a map style while mixing it with additional map features from Mapbox/OSM.

  [1]: https://www.mapbox.com/help/georeferencing-imagery/

**Comment by cmulders** [comment]
Ah nice, probably a much better solution!
